server:
  port: 8081
spring:
  application:
    name: RestNotes
  datasource:
    name: notes
    generate-unique-name: false
  data:
    rest:
      base-path: /default-api
  thymeleaf:
    cache: false
  jpa:
    show-sql: false
    hibernate:
      show-sql: false
    properties:
      hibernate:
        format_sql: false

